version: '3.8'

services:
  go-api:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: autotester-go
    ports:
      - "8081:8081"
    environment:
      - GO_ENV=production
      - PYTHON_API_URL=http://python-api:3000
      - TIMEOUT=3
    restart: unless-stopped
    depends_on:
      - python-api
    networks:
      - autotester-network
    volumes:
      - ./logs:/app/logs

  python-api:
    build:
      context: ./parser_service
      dockerfile: Dockerfile.python
    container_name: autotester-python
    ports:
      - "3000:3000"
    environment:
      - PYTHON_ENV=production
      - MODEL_PATH=/app/models
    restart: unless-stopped
    networks:
      - autotester-network
    volumes:
      - ./parser_service/models:/app/models

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-api
      - python-api